#include "initialize_leds.h"
#include "delay.h"
#include <ti/devices/msp/msp.h>

#define POWER_STARTUP_DELAY (16u)

void InitializeGPIO(void)
{
    /* Reset and power GPIOA */
    GPIOA->GPRCM.RSTCTL = (GPIO_RSTCTL_KEY_UNLOCK_W |
                          GPIO_RSTCTL_RESETSTKYCLR_CLR |
                          GPIO_RSTCTL_RESETASSERT_ASSERT);

    GPIOA->GPRCM.PWREN  = (GPIO_PWREN_KEY_UNLOCK_W |
                          GPIO_PWREN_ENABLE_ENABLE);

    delay_cycles(POWER_STARTUP_DELAY);

    /* Configure IOMUX pin */
    IOMUX->SECCFG.PINCM[IOMUX_PINCM1]  = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA0
    IOMUX->SECCFG.PINCM[IOMUX_PINCM2]  = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA1
    IOMUX->SECCFG.PINCM[IOMUX_PINCM6]  = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA5
    IOMUX->SECCFG.PINCM[IOMUX_PINCM7]  = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA6
    IOMUX->SECCFG.PINCM[IOMUX_PINCM8]  = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA7
    IOMUX->SECCFG.PINCM[IOMUX_PINCM9]  = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA8
    IOMUX->SECCFG.PINCM[IOMUX_PINCM10] = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA9
    IOMUX->SECCFG.PINCM[IOMUX_PINCM11] = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA10
    IOMUX->SECCFG.PINCM[IOMUX_PINCM12] = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA11
    IOMUX->SECCFG.PINCM[IOMUX_PINCM13] = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA12
    IOMUX->SECCFG.PINCM[IOMUX_PINCM14] = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA13
    IOMUX->SECCFG.PINCM[IOMUX_PINCM15] = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA14
    IOMUX->SECCFG.PINCM[IOMUX_PINCM16] = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA15
    IOMUX->SECCFG.PINCM[IOMUX_PINCM17] = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA16
    IOMUX->SECCFG.PINCM[IOMUX_PINCM18] = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA17
    IOMUX->SECCFG.PINCM[IOMUX_PINCM19] = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA18
    IOMUX->SECCFG.PINCM[IOMUX_PINCM22] = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA21
    IOMUX->SECCFG.PINCM[IOMUX_PINCM23] = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA22
    IOMUX->SECCFG.PINCM[IOMUX_PINCM24] = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA23
    IOMUX->SECCFG.PINCM[IOMUX_PINCM25] = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA24
    IOMUX->SECCFG.PINCM[IOMUX_PINCM26] = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA25
    IOMUX->SECCFG.PINCM[IOMUX_PINCM27] = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA26
    IOMUX->SECCFG.PINCM[IOMUX_PINCM28] = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA27
    IOMUX->SECCFG.PINCM[IOMUX_PINCM29] = IOMUX_PINCM_PC_CONNECTED | GPIO_FUNC1;  // PA28

    /* Initialize LEDs OFF and enable outputs */
    GPIOA->DOUTSET31_0 = ALL_LED_BITS_A;   // LEDs OFF
    GPIOA->DOESET31_0  = ALL_LED_BITS_A;   // Enable outputs
}
